**Discovering Activation Functions**

Sigmoid aktivasyon fonksiyonu ikili sınıflandırma sonuçları için döner. Örneğin bir canlı ya memelidir ya değildir.

In [ ]:
import torch
import torch.nn as nn

In [ ]:
input_tensor=torch.tensor([[6]])
sigmoid = nn.Sigmoid()

In [ ]:
output = sigmoid(input_tensor)

In [ ]:
output

tensor([[0.9975]])

Sigmoid Activation As the last layer

In [ ]:
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

In [ ]:
model

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Sigmoid()
)

Softmax Activation

In [ ]:
input_tensor = torch.tensor(
    [[4.3,6.1,2.3]]
)

In [ ]:
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)

In [ ]:
output_tensor

tensor([[0.1392, 0.8420, 0.0188]])

In [ ]:
input_tensor = torch.tensor([[2.4]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9168]])


In [ ]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [1]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.0661, 0.5997, 0.2115, 0.1227]], grad_fn=<SoftmaxBackward0>)


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


**One - Hat Encoding**

Tahmin ettiğimiz y gerçek değerinin ,karşılaştırabilmek için tensör olarak dönüştürme işlemidir.

In [4]:
import torch.nn.functional as F

In [5]:
print(F.one_hot(torch.tensor(0),num_classes = 3 ))

tensor([1, 0, 0])


In [6]:
print(F.one_hot(torch.tensor(1),num_classes = 3 ))

tensor([0, 1, 0])


In [7]:
print(F.one_hot(torch.tensor(2),num_classes = 3 ))

tensor([0, 0, 1])


In [10]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([-5.2,4.6,0.8])
one_hat_target = torch.tensor([1,0,0])


criterion = CrossEntropyLoss()
print(criterion(scores.double(),one_hat_target.double()))

tensor(9.8222, dtype=torch.float64)


In [12]:
import torch
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss

y = [2] #zaten array olduğu için direkt tensor içine koyalım
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes=4)

# Create the cross entropy loss function
criterion = CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


**Gradients**
Loss Functiondan sora gradients hesaplıyoru. gradients dediğimiz şey türevdir,yani eğim yani bizim modelimiz hata değerinin ne kadar yüksek olduğunu hesaplıyoruz. buradan aldığımız değer ile birlikte model içindeki bias ve weights değerlerini güncelliyoruz çünkü model bu değerleri önceden kendisi atıyordu.

model = nn.Sequential(
    nn.Linear(16,8),
    nn.Linear(8,4),
    nn.Linear(4,2),
)
prediction = model(sample)

criterion = CrossEntropyLoss()
loss = criterion(prediction,target)
loss.backward()


model[0].weight.grad
model[0].bias.grad
model[1].weight.grad
model[1].bias.grad
model[2].weight.grad
model[2].bias.grad

In [ ]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(),lr=0.001)

optimizer.step()

In [ ]:
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

In [ ]:
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weight of each linear layer
grads0 = model[0].weight.grad
grads1 = model[1].weight.grad
grads2 = model[2].weight.grad

In [ ]:
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weight of each linear layer
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

# Update the weights using the learning rate and the gradients
weight0 = weight0 - grads0*lr
weight1 = weight1 - grads1*lr
weight2 = weight2 - grads2*lr