pytorch framework entegere edelim

In [1]:
import torch

neural network oluşturmak için gerekli diğer yapıyı ekleyelim

In [2]:
import torch.nn as nn

tensor oluşturalım

In [3]:
input_tensors = torch.tensor(
    [[0.3471,0.4547,-0.2356]]
)

doğrusal bir katman olan Linear Layer ekleyelim

In [5]:
linear_layer = nn.Linear(
    in_features = 3,
    out_features= 2
)

output görelim

In [6]:
output = linear_layer(input_tensors)
print(output)

tensor([[-0.1556,  0.4279]], grad_fn=<AddmmBackward0>)


Weight ve Bias

In [7]:
linear_layer.weight

Parameter containing:
tensor([[ 0.3727, -0.5475, -0.5284],
        [ 0.5049,  0.5138, -0.5434]], requires_grad=True)

In [8]:
linear_layer.bias

Parameter containing:
tensor([-0.1605, -0.1090], requires_grad=True)

Sequential Yapısı

model = nn.Sequential(
    nn.Linear(n_features ,8),
    nn.Linear(8,4),
    nn.Linear(4,n_classes)
)

In [ ]:
model = nn.Sequential(
    nn.Linear(10 ,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)